openapi: "3.0.0"
info:
  version: "1.0"
  title: ClassifierType
  description: This is the yaml detailing the ClassifierType
paths: {}
definitions:
  ClassifierTypeModel:
    type: string
    enum:
      - DECISION_TREE