openapi: "3.0.0"
info:
  version: "1.0"
  title: ClassifierDataResponseModel
  description: This is the yaml detailing the ClassifierDataResponse
paths: {}
definitions:
  ClassifierDataResponseModel:
    type: object
    properties:
      values:
        type: array
        description: computed values of current column name
        items:
          type: integer
      columnName:
        type: string
        description: name of the current data column