#!/usr/bin/python3

#Paths
SERVICE_DIRECTORY = 'service/'
WEB_UI_DIRECTORY = 'web-ui/'
ENGINE_DIRECTORY = 'engine/'
SWING_UI_DIRECTORY = 'swing-ui/'
DIST_DIRECTORY = 'dist/machine-learning-swissknife'

DOCKER_DEPLOYMENT_DIRECTORY = '../../docker_deployment/'
DOCKER_DEPLOYMENT_SERVICE_DIRECTORY = '{}{}'.format(DOCKER_DEPLOYMENT_DIRECTORY, SERVICE_DIRECTORY)
DOCKER_DEPLOYMENT_SERVICE_ENGINE_DIRECTORY = '{}{}'.format(DOCKER_DEPLOYMENT_SERVICE_DIRECTORY, ENGINE_DIRECTORY)
DOCKER_DEPLOYMENT_WEB_UI_DIRECTORY = '{}{}'.format(DOCKER_DEPLOYMENT_DIRECTORY, WEB_UI_DIRECTORY)
DOCKER_DEPLOYMENT_WEB_UI_DIST_DIRECTORY = '{}{}{}'.format(DOCKER_DEPLOYMENT_DIRECTORY, WEB_UI_DIRECTORY, DIST_DIRECTORY)
DOCKER_DEPLOYMENT_SWING_UI_DIRECTORY = '{}{}'.format(DOCKER_DEPLOYMENT_DIRECTORY, SWING_UI_DIRECTORY)

DEPLOYMENT_DIRECTORY = 'deployment/'
DEPLOYMENT_SERVICE_DIRECTORY = '{}{}'.format(DEPLOYMENT_DIRECTORY, SERVICE_DIRECTORY)
DEPLOYMENT_WEB_UI_DIRECTORY = '{}{}'.format(DEPLOYMENT_DIRECTORY, WEB_UI_DIRECTORY)
DEPLOYMENT_SWING_UI_DIRECTORY = '{}{}'.format(DEPLOYMENT_DIRECTORY, SWING_UI_DIRECTORY)

#Deployment
DEFAULT_SERVICE_HOST = 'localhost'
DEFAULT_SERVICE_PORT = '6766'

#Docker Image
SERVICE_IMAGE = 'ramyeid/mlsk-service'
WEB_UI_IMAGE = 'ramyeid/mlsk-web-ui'
SWING_UI_IMAGE = 'ramyeid/mlsk-swing-ui'
