openapi: "3.0.0"
info:
  version: "1.0"
  title: ClassifierStartResponse
  description: This is the yaml detailing the ClassifierStartResponse
paths: {}
definitions:
  ClassifierStartResponseModel:
    type: object
    properties:
      requestId:
        type: long
        description: Unique id assigned to a request