credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "github-token"
          password: "{AQAAABAAAABwUmvQ6tbH4hQ3KOXzd8X75QH6wWG9W+dbGLerjILvFUrAtF3uRIsK0dnwGCsnN4aoPr/e8Xzw7+W8b/YMV6Lw+JPpUFH/7b6xstQNvzukd050OXA6TqDUDO9XUb33N0FK78lUfTLvFeh/LNpc0DteGPpHav4L8qb4aKpXFSIQc7M=}"
          scope: GLOBAL
          username: "ramyeid"
      - string:
          id: "SonarServer"
          scope: GLOBAL
          secret: "{AQAAABAAAAAwYppIvfdBzj0awXgsfiYvcq8+6DqlwAJkIWfZdThpjoARUE6uahsUjc3Spc0wrTDzmtOdEAxc+kA9vBXxYrQVDQ==}"
jenkins:
  clouds:
  - docker:
      name: "docker-engine"
      containerCap: 1
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "tcp://docker.for.mac.host.internal:2375"
        readTimeout: 60
      templates:
      - connector: "attach"
        labelString: "docker"
        dockerTemplateBase:
          image: "ramyeid/mlsk-build-agent"
          mounts:
          - "type=volume,src=mlsk_agent_m2_repo,dst=/root/.m2/repository/"
          - "type=volume,src=mlsk_agent_node_modules,dst=/root/.mlsk_node_modules/node_modules/"
          mountsString: |-
            type=volume,src=mlsk_agent_m2_repo,dst=/root/.m2/repository/
            type=volume,src=mlsk_agent_node_modules,dst=/root/.mlsk_node_modules/node_modules/
        instanceCapStr: "1"
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
unclassified:
  globalLibraries:
    libraries:
    - defaultVersion: "master"
      name: "mlsk-shared-library"
      retriever:
        modernSCM:
          libraryPath: "devops/ci/shared-library/"
          scm:
            git:
              credentialsId: "github-token"
              id: "36d4dcfb-27ce-4861-ac0b-4090987cceaf"
              remote: "https://github.com/ramyeid/mlsk.git"
              traits:
              - cleanAfterCheckoutTrait:
                  extension:
                    deleteUntrackedNestedRepositories: true
              - cleanBeforeCheckoutTrait:
                  extension:
                    deleteUntrackedNestedRepositories: true
              - "pruneStaleBranchTrait"
              - "pruneStaleTagTrait"
              - "wipeWorkspaceTrait"
  sonarGlobalConfiguration:
    buildWrapperEnabled: false
    installations:
    - name: "SonarqubeServer"
      serverUrl: "http://docker.for.mac.host.internal:8789"
      credentialsId: "SonarServer"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
