openapi: "3.0.0"
info:
  version: "1.0"
  title: MLSK - DecisionTree - Engine
  description: This is the API detailing all endpoints
    of the Machine Learning Swiss Knife, Decision Tree, Engine side.
    The Service is written in PYTHON
tags:
  - name: DecisionTree
paths:
  '/decision-tree/start':
    post:
      tags:
        - DecisionTree
      summary: Decision Tree Start Request
      operationId: start
      description: Notify Engine that a decision tree algorithm will be launched
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../model/ClassifierStartRequest.yaml#/definitions/ClassifierStartRequestModel'
      responses:
        '200':
          description: Returns OK, data has been set.
        '500':
          description: Engine Computation Exception with detailed exception message.
  '/decision-tree/data':
    post:
      tags:
        - DecisionTree
      summary: Decision Tree Data Request
      operationId: data
      description: Incrementally send the data of the current decision tree data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../../../model/classifier/ClassifierDataRequest.yaml#/definitions/ClassifierDataRequestModel'
      responses:
        '200':
          description: Returns Ok, data has been set.
        '500':
          description: Engine Computation Exception with detailed exception message.
  '/decision-tree/predict':
    post:
      tags:
        - DecisionTree
      summary: Decision Tree Predict
      operationId: predict
      description: Predict the values with Decision Tree algorithm.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../../../model/classifier/ClassifierRequest.yaml#/definitions/ClassifierRequestModel'
      responses:
        '200':
          description: Returns the predicted values.
          content:
            application/json:
              schema:
                $ref: '../../../model/classifier/ClassifierResponse.yaml#/definitions/ClassifierResponseModel'
        '500':
          description: Engine Computation Exception with detailed exception message.
  '/decision-tree/predict-accuracy':
    post:
      tags:
        - DecisionTree
      summary: Decision Tree Predict Accuracy
      operationId: computePredictAccuracy
      description: |
        Compute Predict Accuracy with Decision Tree Algorithm using the last {numberOfValues}.
        Predict the last {numberOfValues} and compare to actual data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../../../model/classifier/ClassifierRequest.yaml#/definitions/ClassifierRequestModel'
      responses:
        '200':
          description: Returns the accuracy of the predict algorithm.
          content:
            application/json:
              schema:
                type: number
        '500':
          description: Engine Computation Exception with detailed exception message.
  '/decision-tree/cancel':
    post:
      tags:
        - DecisionTree
      summary: Decision Tree Cancel Request
      operationId: cancel
      description: |
        Cancel any request data currently on the engine - Clears state.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../model/classifier/ClassifierCancelRequest.yaml#/definitions/ClassifierCancelRequestModel'
      responses:
        '200':
          description: Returns Ok, data has been cleared.
        '500':
          description: Engine Computation Exception with detailed exception message.