BUILD_DIRECTORY = "../build/"
COMPONENTS_DIRECTORY = "components/"
BUILD_COMPONENTS_DIRECTORY = "../build/" + COMPONENTS_DIRECTORY 
CONFIGURATION_FILE = "swissknife.ini"
SERVICE_SECTION = "SERVICE"
SERVICE_PORT_OPTION = "port"
ENGINE_SECTION = "ENGINE"
ENGINE_PORTS_OPTION = "ports"