#!/usr/bin/python3

BUILD_DIRECTORY = "../build/"
COMPONENTS_DIRECTORY = "components/"
BUILD_COMPONENTS_DIRECTORY = BUILD_DIRECTORY + COMPONENTS_DIRECTORY
LOGS_DIRECTORY = "logs/"
BUILD_LOGS_DIRECTORY = BUILD_DIRECTORY + LOGS_DIRECTORY
ENGINE_DIRECTORY = "engine/"
BUILD_COMPONENTS_ENGINE_DIRECTORY = BUILD_COMPONENTS_DIRECTORY + ENGINE_DIRECTORY
WEB_UI_DIRECTORY = "web-ui/"
BUILD_COMPONENTS_WEB_UI_DIRECTORY = BUILD_COMPONENTS_DIRECTORY + WEB_UI_DIRECTORY
SERVICE_JAR = "mlsk-service-impl.jar"
UI_JAR = "mlsk-ui-jar-with-dependencies.jar"
CONFIGURATION_FILE = "swissknife.ini"
PORT_SECTION = "port"
PORTS_SECTION = "ports"
SERVICE_SECTION = "SERVICE"
ENGINE_SECTION = "ENGINE"
WEB_UI_SECTION = "WEB_UI"
SERVICE_PORT_OPTION = "service_port"
ENGINE_PORTS_OPTION = "engine_ports"
WEB_UI_PORT_OPTION = "webui_port"
