openapi: "3.0.0"
info:
  version: "1.0"
  title: TimeSeriesAnalysisRequestModel
  description: This is the yaml detailing the TimeSeriesAnalysisRequest
paths: {}
definitions:
  TimeSeriesAnalysisRequestModel:
    type: object
    required:
      - timeSeries
      - numberOfValues
    properties:
      timeSeries:
        $ref: '../../model/timeseries/TimeSeries.yaml#/definitions/TimeSeriesModel'
      numberOfValues:
        type: integer
        description: Number Of values to predict/forecast/etc. using the algorithm